name: Update Latest Telegram Post

# Даем явное разрешение на запись в репозиторий
permissions:
  contents: write

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml
      
      - name: Run parser
        run: python parser.py
        env:
          CHANNEL_NAME: "ProxyMTProto"
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add index.html latest_post.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update post" && git push)
